# Generated by Django 4.1.4 on 2022-12-13 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produtor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='arquivos/principal/%Y/%m/%d/')),
                ('nome_diretor', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(blank=True, default='', max_length=255)),
                ('data', models.DateTimeField(blank=True, default='')),
                ('dimensao_suporte', models.TextField(blank=True, default='')),
                ('entidade_custodiadora', models.CharField(blank=True, default='', max_length=255)),
                ('localizacao_fisica', models.CharField(blank=True, default='', max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('nota_explicativa', models.CharField(blank=True, default='', max_length=255)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquivo.categoria')),
                ('nome_produtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquivo.produtor')),
            ],
        ),
    ]
