# Generated by Django 4.1.4 on 2022-12-14 01:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(max_length=255, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='arquivo',
            field=models.FileField(upload_to='arquivos/principal/%Y/%m/%d/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='autor',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquivo.categoria', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='data',
            field=models.DateTimeField(blank=True, default='', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='dimensao_suporte',
            field=models.TextField(blank=True, default='', verbose_name='Dimensão e suporte'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='entidade_custodiadora',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Entidade custoriadora'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='localizacao_fisica',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Localização física'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='nome_diretor',
            field=models.CharField(max_length=255, verbose_name='Diretor'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='nome_produtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquivo.produtor', verbose_name='Produtor'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='nota_explicativa',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nota explicativa'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='produtor',
            name='nome_produtor',
            field=models.CharField(max_length=255, verbose_name='Produtor'),
        ),
    ]
