# Generated by Django 4.1.4 on 2022-12-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0003_objeto_publicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objeto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='objeto',
            name='categorias',
            field=models.ManyToManyField(to='arquivo.categoria', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='autor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='data',
            field=models.DateTimeField(blank=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='dimensao_suporte',
            field=models.TextField(blank=True, verbose_name='Dimensão e suporte'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='entidade_custodiadora',
            field=models.CharField(blank=True, max_length=255, verbose_name='Entidade custoriadora'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='localizacao_fisica',
            field=models.CharField(blank=True, max_length=255, verbose_name='Localização física'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='nota_explicativa',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nota explicativa'),
        ),
    ]
