# Generated by Django 4.1.4 on 2022-12-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0004_remove_objeto_categoria_objeto_categorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
