# Generated by Django 4.1.4 on 2022-12-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0005_objeto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='slug',
            field=models.SlugField(default='', max_length=255, null=True, unique=True),
        ),
    ]
