# Generated by Django 4.1.4 on 2022-12-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0007_alter_objeto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='produtor',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
