# Generated by Django 4.1.4 on 2022-12-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0011_alter_objeto_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objeto',
            name='thumbnail',
        ),
    ]
