# Generated by Django 4.1.4 on 2022-12-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0013_objeto_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='extensao_arquivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='thumbnail',
            field=models.FileField(blank=True, default='', upload_to='arquivos/thumbnail/%Y/%m/%d/', verbose_name='Thumbnail'),
        ),
    ]
